package com.cartogenesis.worldgen

import com.cartogenesis.worldgen.model.WorldGenConfig
import com.cartogenesis.worldgen.model.WorldMap
import com.cartogenesis.worldgen.pipeline.Biome
import com.cartogenesis.worldgen.pipeline.ClimateStage
import com.cartogenesis.worldgen.pipeline.GlaciationStage
import com.cartogenesis.worldgen.pipeline.OceanStage
import com.cartogenesis.worldgen.pipeline.SeaLevelStage
import java.util.Locale
import org.junit.Assert.assertTrue
import org.junit.Test
import kotlinx.coroutines.runBlocking

/**
 * The ice's comb guard, in a class of its own rather than beside the lake guard in
 * [GlaciationTest], so that its six worlds of 1,024 rows and the other two guards' twelve can
 * be generated by different test workers.
 */
class GlaciationCombTest : BorrowsSharedWorlds() {

    /**
     * The comb guard: a mountain flank carries a few trunk glaciers, not one glacier per gully.
     *
     * The residual the sheet-versus-valley split left behind, and the reason for a second pass. With
     * flat country handed to the ice sheet, the range fronts still showed the lattice at their own
     * scale: groups of five to fifteen short bars of water, one cell wide, lying parallel at exactly
     * 45 degrees down the flank of the central range on seed 718106 and in the cold uplands of seeds
     * 7 and 42. A straight range front carries a rank of parallel gullies; the old selection asked
     * only whether a path drained enough frozen ground against the *world's* total, and every gully
     * in the rank passed at once, so every gully got a trough, a basin staircase and a moraine bar.
     * Real ranges carry a handful of glaciers, in their trunk valleys, and no two trunk valleys are
     * parallel straight lines a few cells apart.
     *
     * Two figures, both at 1024, which is the resolution the desktop opens at and the one the comb
     * showed up in:
     *
     *  - **filaments**: lake bodies every cell of which lies on one D8 line, one cell wide, four
     *    cells or longer. A body of water that is a line along a flow path is not a lake in a
     *    valley.
     *  - **parallel bars**: the share of lake water lying in a thin bar at a grid bearing that has
     *    another such bar of the *same* bearing three to ten cells off to the side. That is the comb
     *    itself: not one straight lake, which a trough may legitimately leave, but a rank of them.
     *
     * Measured on the code as it stood after the first pass, and after this one:
     *
     * | seed (1024) | filaments | parallel bars | lake cells |
     * |---|---|---|---|
     * | 718106 | 1 -> 0 | 4.1% -> 1.7% | 8404 -> 6632 |
     * | 42 | 6 -> 0 | 7.1% -> 2.3% | 4797 -> 3436 |
     * | 7 | 1 -> 0 | 3.0% -> 1.6% | 17500 -> 14946 |
     */
    @Test
    fun `mountain flanks carry a few trunk glaciers, not a comb of them`() {
        // 3.5% until H5, 5% after it, 4.5% after H5b, and the bar has only ever moved with a
        // measurement beside it.
        //
        // H5's lowstand grades the lower valleys to a sea a stand below today's, which cuts the D8
        // channels near the coast deeper than they were and leaves more of them for the fill to
        // pond: measured at 1024 on 718106/42/7, the share went 2.5/2.8/1.7% before H5 to
        // 2.3/4.5/2.6% after, and the bar went up to hold the worst of the three.
        //
        // H5b's receiver clamp is the repair for what that exposed — a channel cell cut below the
        // cell it drains into is a hole the next fill has to pond, and the incision was making
        // thousands of them a world (`ReceiverClampTest` has the census). With it the share reads
        // 2.2/4.4/1.7%: seed 718106 and seed 7 are back below where they stood before H5, and the
        // bar comes down to sit above the worst of the three again.
        //
        // It does not reach the 3.5% it was at, and the residual is measured rather than guessed.
        // What is left on seed 42 is the *spoil*: with the incision clamped, the deposition laid at
        // the end of the last round is what puts channel cells below their receivers — 420 of them
        // over the rounds on that seed against 344 with the clamp off, because a less deeply
        // incised channel leaves a floodplain standing relatively higher. That is an alluvial dam,
        // which is a real landform, and the no-uphill rule that bounds it computes its margin in
        // shoreline-relative units and spends it as a height-unit budget — so the margin is about
        // four times what it means to be. Measured and handed on rather than fixed here: the
        // deposition is E5's chunk and the erodibility that unit muddle calibrated is G1's.
        // Back to 3.5%, where H5 left it before the alluvial dams pushed it up.
        //
        // E6 closed the unit muddle in `headroom` that let a dam stand `1 / landRange` times higher
        // than the no-uphill rule allows — about four times — and put the lacustrine fan's floor on
        // a fraction of its rim instead of a charge per cell. Both take spoil-made hollows out of
        // the world, and the comb residual is mostly those: measured at 1024 with the notch and the
        // history off, seeds 718106/42/7 read 1.2%, 2.5% and 1.5% where H5b left them at 2.2%, 4.4%
        // and 1.7%. The bar goes back to the figure the guard was written with, with the worst seed
        // now at two thirds of it.
        // And then the 2.0.x line arrived, and the figure this bar is set on stopped being the
        // ice's. Measured on the merged tree at 1024, in this case's own configuration, each seed
        // beside the same world with `GlaciationConfig.enabled` off:
        //
        //   718106   1.34% with the ice (71 cells of 5264), 1.21% without (61 of 5043)
        //   42       5.66% with the ice (121 of 2144),      6.03% without (124 of 2060)
        //   7        1.74% with the ice (59 of 3406),       1.65% without (59 of 3582)
        //
        // Seed 42 is over the old bar and none of it is the ice's: switch the ice off and the comb
        // is three cells *larger*. What moved is the drainage under it — the facet routing takes
        // that seed's un-glaciated comb from 49 cells to 124 — and a bar on the total was reading
        // the router through a glacial denominator, which is the same fault this case's other
        // clause was demoted for.
        //
        // So the clause asks what it always meant to ask: how much comb the *ice* adds, against
        // the un-glaciated world of the same seed. That is what `GlaciationAuditTest` already does
        // with the bar count at 2048, and for the stated reason — "so the clause still says
        // something about the ice and not about the terrain under it". The bound is that audit's
        // own: a fiftieth of the world's standing water. The three seeds measure +0.18%, -0.13%
        // and +0.01% of it, which is an order of magnitude inside the bound and leaves the guard
        // room to catch the lattice it was written for, whose comb was the ice's entirely.
        //
        // The total is still printed. Seed 42's 5.7% is a real thing about the map and wants a
        // guard of its own, on the drainage, where the ice is not in the way; `TODO.md` carries it.
        val ICE_COMB_BAR = 0.02f
        var worst = 0f
        val over = ArrayList<String>()
        listOf(718106L, 42L, 7L).forEach { seed ->
            val config = WorldGenConfig.forRows(seed, 512)
                .atResolution(2048, 1024)
                // Both figures below are shares of the world's standing water, which moves with
                // how the outlets are cut for reasons that have nothing to do with ice: E1's notch
                // took seed 718106's lake cells at 1024 from 6632 to 2173 while the comb held 113
                // cells before and 128 after, so an unchanged comb read as 1.7% one moment and 5.9%
                // the next. The notch is gone (E1b); the outlets are cut by the incision on each
                // lake's surplus, which this guard cannot switch off, and it reads what is left.
                // And H1's tectonic history off, for a reason of the same shape. Both figures are
                // shares of the world's standing water, and the history changes how much of that
                // there is and where: its worn old belts are broad, low-relief uplands, which is
                // exactly the ground B4's two regimes divide between them, and a cold one sits
                // near the boundary. On seed 42 the comb share reads 3.2% with the history off and
                // 3.6% with it on, either side of a bar of 3.5% — a fortieth of the world's water
                // moving between two categories, not a comb appearing. What the shipped world
                // measures is asserted where it can be read against the un-glaciated world of the
                // same seed: see `the author's 2048 world has no narrow straight water`.
                .let { it.copy(tectonics = it.tectonics.copy(historyEpochs = 1)) }
            val world = SharedWorlds.world(config)
            val bare = SharedWorlds.world(
                config.copy(glaciation = config.glaciation.copy(enabled = false))
            )
            val filaments = countFilaments(world)
            val comb = combShare(world)
            val lakeCells = world.rivers.lakes.lakeId.count { it >= 0 }
            val bareLakeCells = bare.rivers.lakes.lakeId.count { it >= 0 }
            // Cells rather than shares on both sides, because the two worlds do not hold the same
            // amount of water and a difference of two shares would be a difference of denominators
            // as much as of combs.
            val addedByTheIce =
                (comb * lakeCells - combShare(bare) * bareLakeCells) / lakeCells
            println(
                "COMB seed $seed at 1024: filaments=$filaments of ${world.rivers.lakes.lakes.size}" +
                    " lakes, parallel bars ${"%.3f".format(comb)} of $lakeCells lake cells," +
                    " ${"%.3f".format(combShare(bare))} of $bareLakeCells with the ice off," +
                    " so the ice adds ${"%.4f".format(addedByTheIce)} of the world's water"
            )
            assertTrue(
                "seed $seed at 1024 has $filaments lakes that are a straight one-cell line along a" +
                    " D8 bearing — a trough is a valley the ice found, not a line drawn down a" +
                    " flow path",
                filaments == 0
            )
            worst = maxOf(worst, addedByTheIce)
            if (addedByTheIce >= ICE_COMB_BAR) {
                over.add("$seed at ${"%.2f".format(addedByTheIce * 100)}%")
            }
        }
        // Collected and asserted once, rather than seed by seed, so a run reports all three figures
        // instead of stopping at the first that is over. On the implicit update before the uplift
        // was re-derived on it the ice added 5.00% and 3.18% on seeds 718106 and 7, a comb; with the
        // re-derived uplift it was inside the bar again (docs/DESIGN_LEDGER.md, Fix 3b). Recorded
        // since the lake falls with its outlet, and armed again on square cells at Q2, where the ice
        // adds 1.64, 1.17 and 0.73% (docs/DESIGN_LEDGER.md, Q2). Recorded at L1's review round,
        // once the rift valleys were Earth's width: seed 42's ice adds 2.23%, over the bar; which of
        // its valleys the narrower rifts moved is not isolated (docs/DESIGN_LEDGER.md, L1). Armed
        // again at E1a, whose two heights moved the valleys the ice runs down (docs/DESIGN_LEDGER.md, E1a).
        assertTrue(
            "the ice puts ${ICE_COMB_BAR * 100}% or more of these worlds' standing water into thin" +
                " grid-bearing bars that run parallel to another such bar within ten cells — a" +
                " comb of gullies, not a handful of trunk glaciers: $over" +
                " (worst ${"%.2f".format(worst * 100)}%)",
            over.isEmpty()
        )
    }
}
