package com.cartogenesis.cartography

import com.cartogenesis.worldgen.WorldGenerationEngine
import com.cartogenesis.worldgen.generateBlocking
import com.cartogenesis.worldgen.model.WorldGenConfig
import com.cartogenesis.worldgen.model.WorldMap
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import kotlinx.coroutines.runBlocking
import org.junit.Assume.assumeTrue
import org.junit.Test

/**
 * I3's renders: the striped ice flank, the same ground with the ice off, the ice field on its own
 * and the light that falls on it.
 *
 * A harness and not a guard, and it is gated on `I3_RENDER` being set in the environment so that
 * the per-merge tier never pays for a 1024 world. The guard I3 argues from is
 * `IceSheetTest`'s column-alternation clause; these are the pictures that say what the numbers
 * are about.
 *
 * The world is the one the defect was reported on: seed 878210 at 1024, built the way the desktop
 * application builds it, from a 512 base through `atResolution`, because the knobs a stage reads
 * are scaled by that call and a bare `WorldGenConfig(seed, 1024, 1024)` is a different world.
 *
 * The control is the same world with `GlaciationConfig.enabled` off, generated by handing the
 * finished world back to the engine as `previous`, so every stage but the ice is reused by
 * identity and the only difference between the two pictures is the one under test.
 */
class I3RenderDump {

    private companion object {
        const val SEED = 878210L
        const val SIDE = 1024

        /** The crop, in cells, and the factor it is blown up by. */
        const val CROP_SIDE = 180
        const val CROP_ZOOM = 3

        /** Its north-west corner, in cells. */
        const val FLANK_X = 320
        const val FLANK_Y = 760

        /** Anything this much of the map's height thick is ice rather than a carving. */
        const val ICE_FIELD_UNITS = 0.01f
    }

    private val outputDir = File("../desktop/build/i3-crops")

    @Test
    fun `dump the striped ice flank whole, cropped, as a field and as light`() {
        assumeTrue(System.getenv("I3_RENDER") != null)
        outputDir.mkdirs()
        val config = WorldGenConfig(seed = SEED, width = 512, height = 512)
            .atResolution(SIDE, SIDE)
        val after = WorldGenerationEngine.generateBlocking(config)
        val before = runBlocking {
            WorldGenerationEngine.generate(
                config.copy(glaciation = config.glaciation.copy(enabled = false)),
                previous = after
            )
        }
        val ice = iceField(before, after)
        val window = reportedFlank()
        report(after, ice)

        val atlas = RenderOptions(view = MapView.FANTASY, style = MapStyle.ATLAS)
        write(rasterOf(after, atlas), window, "atlas", "after")
        write(rasterOf(before, atlas), window, "atlas", "before")
        write(greyscale(after, ice), window, "ice-field", "after")
        write(lightOf(after), window, "illumination", "after")
        write(lightOf(before), window, "illumination", "before")
    }

    /**
     * The ice, in the elevation field's own units: what the glaciation stage added to the ground.
     *
     * The stage's thickness array is internal to the world generator, and this is the same
     * quantity seen from outside — the surface it wrote, less the bed it wrote it on — minus
     * whatever carving happened under it, which is negative and is clipped away.
     */
    private fun iceField(before: WorldMap, after: WorldMap): FloatArray {
        val bed = before.relativeElevation.data
        val top = after.relativeElevation.data
        return FloatArray(bed.size) { (top[it] - bed[it]).coerceAtLeast(0f) }
    }

    /**
     * What the ice reads on this world, so the pictures have numbers beside them, and the
     * column-alternation figure the guard is written around.
     *
     * A cell alternates in a direction when it stands above both of its neighbours in that
     * direction, or below both, by more than a twentieth of the local relief. On a dome the two
     * directions come out alike; on a column-striped flank the horizontal figure runs far ahead.
     */
    private fun report(world: WorldMap, ice: FloatArray) {
        val across = world.width
        var cells = 0
        var acrossAlternating = 0
        var downAlternating = 0
        for (cell in ice.indices) {
            if (ice[cell] < ICE_FIELD_UNITS) continue
            val column = cell % across
            val row = cell / across
            if (column == 0 || column == across - 1 || row == 0 || row == world.height - 1) continue
            if (ice[cell - 1] < ICE_FIELD_UNITS || ice[cell + 1] < ICE_FIELD_UNITS) continue
            if (ice[cell - across] < ICE_FIELD_UNITS || ice[cell + across] < ICE_FIELD_UNITS) continue
            cells++
            if (alternates(ice, cell, 1)) acrossAlternating++
            if (alternates(ice, cell, across)) downAlternating++
        }
        println(
            "I3 FIELD seed %d at %d: %d interior sheet cells, %.2f%% alternating across, %.2f%% down"
                .format(
                    SEED, SIDE, cells,
                    acrossAlternating * 100f / cells, downAlternating * 100f / cells
                )
        )
    }

    private fun alternates(ice: FloatArray, cell: Int, step: Int): Boolean {
        val here = ice[cell]
        val low = ice[cell - step]
        val high = ice[cell + step]
        val span = maxOf(here, low, high) - minOf(here, low, high)
        if (span <= 0f) return false
        val edge = 0.05f * span
        return (here - low > edge && here - high > edge) || (low - here > edge && high - here > edge)
    }

    private class Window(val x: Int, val y: Int, val side: Int)

    /**
     * The flank the defect was reported on: the west side of the southern sheet, where it comes
     * down to two lakes.
     *
     * Pinned rather than chosen by a count, because the window has to be the same one before and
     * after or the two pictures are not a comparison. The figures are cells on the 1024 grid and
     * they were read off the whole-map render, not off the field.
     */
    private fun reportedFlank(): Window {
        println("I3 CROP: window $FLANK_X,$FLANK_Y of $CROP_SIDE cells at ${CROP_ZOOM}x")
        return Window(FLANK_X, FLANK_Y, CROP_SIDE)
    }

    private fun rasterOf(world: WorldMap, options: RenderOptions): BufferedImage {
        val pixels = MapRasterizer.rasterize(world, options)
        val image = BufferedImage(world.width, world.height, BufferedImage.TYPE_INT_RGB)
        image.setRGB(0, 0, world.width, world.height, pixels, 0, world.width)
        return image
    }

    /** The ice field on its own: black where there is none, white at the thickest on the map. */
    private fun greyscale(world: WorldMap, ice: FloatArray): BufferedImage {
        val image = BufferedImage(world.width, world.height, BufferedImage.TYPE_INT_RGB)
        var thickest = 0f
        for (value in ice) if (value > thickest) thickest = value
        if (thickest <= 0f) thickest = 1f
        for (cell in ice.indices) {
            val tone = (255f * (ice[cell] / thickest)).toInt().coerceIn(0, 255)
            image.setRGB(
                cell % world.width, cell / world.width, (tone shl 16) or (tone shl 8) or tone
            )
        }
        println("I3 FIELD thickest ice on the map: %.4f field units".format(thickest))
        return image
    }

    /**
     * The light the relief shading puts on the same ground, on its own: the illumination the
     * renderer multiplies a tint by, black at nothing and white at twice ordinary ground.
     */
    private fun lightOf(world: WorldMap): BufferedImage {
        val light = ReliefShading.of(
            world.relativeElevation, world.sea.isLand, singleLamp = false,
            cellHeightInCellWidths = world.config.cellHeightInCellWidths
        )
        val image = BufferedImage(world.width, world.height, BufferedImage.TYPE_INT_RGB)
        for (cell in light.indices) {
            val tone = (255f * (light[cell] / (2f * ReliefShading.ordinaryGround)))
                .toInt().coerceIn(0, 255)
            image.setRGB(
                cell % world.width, cell / world.width, (tone shl 16) or (tone shl 8) or tone
            )
        }
        return image
    }

    private fun write(image: BufferedImage, window: Window, name: String, label: String) {
        ImageIO.write(image, "png", File(outputDir, "$name-whole-$label.png"))
        val crop = image.getSubimage(window.x, window.y, window.side, window.side)
        ImageIO.write(zoomed(crop), "png", File(outputDir, "$name-crop-$label.png"))
        println("I3 RENDER wrote $name-*-$label.png")
    }

    /** Nearest neighbour, because the artefact under examination is one cell wide. */
    private fun zoomed(image: BufferedImage): BufferedImage {
        val big = BufferedImage(
            image.width * CROP_ZOOM, image.height * CROP_ZOOM, BufferedImage.TYPE_INT_RGB
        )
        for (y in 0 until big.height) {
            for (x in 0 until big.width) {
                big.setRGB(x, y, image.getRGB(x / CROP_ZOOM, y / CROP_ZOOM))
            }
        }
        return big
    }
}
