package com.cartogenesis.cartography

import com.cartogenesis.worldgen.WorldGenerationEngine
import com.cartogenesis.worldgen.generateBlocking
import com.cartogenesis.worldgen.model.WorldGenConfig
import com.cartogenesis.worldgen.model.WorldMap
import com.cartogenesis.worldgen.pipeline.Biome
import com.cartogenesis.worldgen.pipeline.VegetationDensity
import java.awt.image.BufferedImage
import java.io.File
import javax.imageio.ImageIO
import kotlinx.coroutines.runBlocking
import org.junit.Test

/**
 * W4's renders: five worlds in the Biomes and Natural views and in a vegetation view of its own,
 * whole and cropped on the ground where the change is supposed to show.
 *
 * A harness and not a guard. The claim W4 makes about the picture is that a steppe now thins into a
 * woodland instead of stopping at a line, and no share of land can settle that; these are the
 * pictures the claim is judged on.
 *
 * **Before and after are taken from the same build**, which is the difference between this harness
 * and `W3RenderDump`'s. W4 changes no world: the vegetation field is new, nothing upstream of it
 * reads it, and the ground's return to the moisture march kept its own proxy — so the Biomes view
 * is the same picture either side of the chunk and a checkout of the branch point would measure
 * nothing. What changed is the drawing, and its control is `VegetationConfig.enabled`, which puts
 * the per-biome canopy table back exactly. The "before" world is that setting off, generated by
 * handing the "after" world back to the engine, so the terrain, the erosion, the sea and the
 * currents are literally the same objects and the only difference between the two pictures is the
 * one under test.
 *
 * Excluded from the per-merge tier by name, like the rest of the render harness.
 */
class W4RenderDump {

    private companion object {
        /** The three standard seeds at the per-merge grid, and the author's two at the working one. */
        val SEEDS = listOf(7L to 512, 42L to 512, 1234L to 512, 718106L to 2048, 59758L to 2048)

        /** The side of the crop, in cells, and how many coarse tiles the crop is chosen from. */
        const val CROP_SIDE = 384
        const val TILES_ACROSS = 8
    }

    private val outputDir = File("../desktop/build/w4-crops")

    @Test
    fun `dump five worlds in the biome, natural and vegetation views`() {
        outputDir.mkdirs()
        SEEDS.forEach { (seed, side) ->
            val started = System.currentTimeMillis()
            val config = WorldGenConfig(seed = seed, width = side, height = side)
            val after = WorldGenerationEngine.generateBlocking(config)
            // The same world with the field off. Handed the finished world as `previous`, so every
            // stage but the climate is reused by identity and the control costs one climate rather
            // than one world.
            val before = runBlocking {
                WorldGenerationEngine.generate(
                    config.copy(vegetation = config.vegetation.copy(enabled = false)),
                    previous = after
                )
            }
            println(
                "W4 RENDER seed $seed at $side in ${(System.currentTimeMillis() - started) / 1000}s"
            )
            report(seed, after)
            val window = openToWoodedWindow(after)

            listOf(
                "biome" to RenderOptions(view = MapView.BIOMES, style = MapStyle.ATLAS),
                "natural" to RenderOptions(view = MapView.FANTASY, style = MapStyle.NATURAL),
                "atlas" to RenderOptions(view = MapView.FANTASY, style = MapStyle.ATLAS)
            ).forEach { (view, options) ->
                // One raster in the heap at a time: a 2048 picture is 16 MB and there are three
                // views of two worlds here.
                write(rasterOf(before, options), window, "$seed-$side-$view", "before")
                write(rasterOf(after, options), window, "$seed-$side-$view", "after")
            }
            // The new view has no "before": there is no field to draw before the chunk. Two crops
            // of it, because the two things it carries live in different places: the graded
            // boundary is in the same window the tint crops use, and the permafrost is at the top
            // and bottom of the map where that window never lands.
            val field = vegetationImage(after)
            write(field, window, "$seed-$side-vegetation", "after")
            write(field, frozenGroundWindow(after), "$seed-$side-permafrost", "after")
        }
    }

    /**
     * What the field reads on this world, so the pictures have numbers beside them: the share of
     * land bare, the share under a closed canopy and the share over frozen ground.
     */
    private fun report(seed: Long, world: WorldMap) {
        var land = 0
        var bare = 0
        var forest = 0
        var permafrost = 0
        for (cell in world.sea.isLand.indices) {
            if (!world.sea.isLand[cell]) continue
            land++
            val density = world.climate.vegetationDensity.data[cell]
            if (density < 0.1f) bare++
            if (density >= 0.6f) forest++
            if (world.climate.permafrost[cell].toInt() !=
                VegetationDensity.Permafrost.NONE.ordinal
            ) {
                permafrost++
            }
        }
        println(
            "W4 FIELD seed %d: %.1f%% of land bare, %.1f%% closed forest, %.1f%% over permafrost"
                .format(seed, bare * 100f / land, forest * 100f / land, permafrost * 100f / land)
        )
    }

    private class Window(val x: Int, val y: Int, val side: Int)

    /**
     * A window on the ground where an open country meets a wooded one most often.
     *
     * The map is cut into coarse tiles and the tile with the most four-neighbour pairs crossing
     * that line is taken, which is the same answer on every platform and lands on the ground the
     * chunk's claim is about rather than on a place chosen by eye.
     */
    private fun openToWoodedWindow(world: WorldMap): Window {
        val open = setOf(Biome.GRASSLAND, Biome.SHRUBLAND, Biome.SAVANNA, Biome.DESERT)
        val wooded = setOf(
            Biome.TEMPERATE_FOREST, Biome.TEMPERATE_RAINFOREST, Biome.TAIGA,
            Biome.TROPICAL_SEASONAL_FOREST, Biome.TROPICAL_RAINFOREST, Biome.MONSOON_FOREST
        )
        val cellsAcross = world.width
        val cellsDown = world.height
        val tileSide = cellsAcross / TILES_ACROSS
        val counts = IntArray(TILES_ACROSS * TILES_ACROSS)
        for (row in 0 until cellsDown - 1) {
            for (column in 0 until cellsAcross - 1) {
                val cell = row * cellsAcross + column
                val here = world.climate.biome[cell]
                intArrayOf(cell + 1, cell + cellsAcross).forEach { next ->
                    val there = world.climate.biome[next]
                    if ((here in open && there in wooded) || (here in wooded && there in open)) {
                        counts[(row / tileSide) * TILES_ACROSS + column / tileSide]++
                    }
                }
            }
        }
        var best = 0
        for (tile in counts.indices) if (counts[tile] > counts[best]) best = tile
        val centreX = (best % TILES_ACROSS) * tileSide + tileSide / 2
        val centreY = (best / TILES_ACROSS) * tileSide + tileSide / 2
        val side = CROP_SIDE.coerceAtMost(minOf(cellsAcross, cellsDown))
        val x = (centreX - side / 2).coerceIn(0, cellsAcross - side)
        val y = (centreY - side / 2).coerceIn(0, cellsDown - side)
        println("W4 CROP: ${counts[best]} open-to-wooded pairs in the chosen tile, window $x,$y")
        return Window(x, y, side)
    }

    /** And a window on the tile holding the most continuous permafrost, chosen the same way. */
    private fun frozenGroundWindow(world: WorldMap): Window {
        val cellsAcross = world.width
        val cellsDown = world.height
        val tileSide = cellsAcross / TILES_ACROSS
        val counts = IntArray(TILES_ACROSS * TILES_ACROSS)
        for (cell in 0 until cellsAcross * cellsDown) {
            if (!world.sea.isLand[cell]) continue
            if (VegetationDensity.Permafrost.ofOrdinal(world.climate.permafrost[cell].toInt()) !=
                VegetationDensity.Permafrost.CONTINUOUS
            ) {
                continue
            }
            counts[(cell / cellsAcross / tileSide) * TILES_ACROSS +
                (cell % cellsAcross) / tileSide]++
        }
        var best = 0
        for (tile in counts.indices) if (counts[tile] > counts[best]) best = tile
        val side = CROP_SIDE.coerceAtMost(minOf(cellsAcross, cellsDown))
        val x = ((best % TILES_ACROSS) * tileSide + tileSide / 2 - side / 2)
            .coerceIn(0, cellsAcross - side)
        val y = ((best / TILES_ACROSS) * tileSide + tileSide / 2 - side / 2)
            .coerceIn(0, cellsDown - side)
        println("W4 CROP: ${counts[best]} continuous-permafrost cells in the chosen tile, window $x,$y")
        return Window(x, y, side)
    }

    private fun rasterOf(world: WorldMap, options: RenderOptions): BufferedImage {
        val pixels = MapRasterizer.rasterize(world, options)
        val image = BufferedImage(world.width, world.height, BufferedImage.TYPE_INT_RGB)
        image.setRGB(0, 0, world.width, world.height, pixels, 0, world.width)
        return image
    }

    /**
     * The field itself: straw at nothing through olive to a deep green at a closed canopy, washed
     * with a cold blue where the ground is frozen the year round — hard over the continuous zone,
     * a fifth of the way over the discontinuous one.
     *
     * A wash and not a ruling. The first version of this drew every fourth row blue, which is the
     * honest way to show a mask over a colour and is invisible in a half-size picture of a 2048
     * world, since halving averages three unruled rows into every ruled one. The wash survives
     * both scales, and blue is a colour the density ramp itself never reaches, so nothing in the
     * picture is ambiguous about which of the two it came from.
     */
    private fun vegetationImage(world: WorldMap): BufferedImage {
        val image = BufferedImage(world.width, world.height, BufferedImage.TYPE_INT_RGB)
        for (cell in 0 until world.width * world.height) {
            val colour = if (!world.sea.isLand[cell]) {
                0x101820
            } else {
                val density = world.climate.vegetationDensity.data[cell].coerceIn(0f, 1f)
                var red = 214 * (1f - density) + 24 * density
                var green = 198 * (1f - density) + 92 * density
                var blue = 150 * (1f - density) + 38 * density
                val zone =
                    VegetationDensity.Permafrost.ofOrdinal(world.climate.permafrost[cell].toInt())
                val frozen = when (zone) {
                    VegetationDensity.Permafrost.CONTINUOUS -> 0.55f
                    VegetationDensity.Permafrost.DISCONTINUOUS -> 0.22f
                    VegetationDensity.Permafrost.NONE -> 0f
                }
                red += (90 - red) * frozen
                green += (169 - green) * frozen
                blue += (230 - blue) * frozen
                (red.toInt() shl 16) or (green.toInt() shl 8) or blue.toInt()
            }
            image.setRGB(cell % world.width, cell / world.width, colour)
        }
        return image
    }

    private fun write(image: BufferedImage, window: Window, name: String, label: String) {
        ImageIO.write(halved(image), "png", File(outputDir, "$name-whole-$label.png"))
        ImageIO.write(
            image.getSubimage(window.x, window.y, window.side, window.side), "png",
            File(outputDir, "$name-crop-$label.png")
        )
        println("W4 RENDER wrote $name-*-$label.png")
    }

    /** Half size, so a whole world is a picture a reader can take in at once. */
    private fun halved(image: BufferedImage): BufferedImage {
        val half = BufferedImage(image.width / 2, image.height / 2, BufferedImage.TYPE_INT_RGB)
        val graphics = half.createGraphics()
        graphics.drawImage(image, 0, 0, half.width, half.height, null)
        graphics.dispose()
        return half
    }
}
